import io

path = r"C:\Users\Micke\Documents\Kodprojekt\nVidia Infer Flash\core\src\targets\qwen3_8_flash_next\impl\runtime\program.cpp"
with io.open(path, "r", encoding="utf-8") as f:
    src = f.read()

old = (
    "// M2 real-mode factory. Opens the real 48x512 artifact + ngram via RealLoadedModel,\n"
    "// builds the proven single-lane RealProgram (self-contained recurrent/KV/MoE state),\n"
    "// and wraps it in the family's Program facade with the mini device buffers as size-1\n"
    "// sentinels (never touched in real mode). `max_context` sizes the RealProgram's QSA\n"
    "// paged-KV pool and the plan_request room; it must be >= the largest prompt the\n"
    "// serve should accept (e.g. 100000 for the 100k gate).\n"
    "std::unique_ptr<Program> create_real_program(const std::filesystem::path& artifact,\n"
    "                                             const std::filesystem::path& ngram,\n"
    "                                             std::uint32_t max_context, DeviceContext& device,\n"
    "                                             ops::QsaIndexerKvDtype idx_dtype) {\n"
    "  if (max_context == 0) {\n"
    "    throw std::runtime_error(\"flash_next real: max_context must be > 0\");\n"
    "  }\n"
    "\n"
    "  // Load the real artifact + ngram (weights arena + RealModelView + artifact reader).\n"
    "  // `open` throws on a missing/corrupt artifact or a CUDA allocation error.\n"
    "  auto model = RealLoadedModel::open(artifact, ngram, device);\n"
    "\n"
    "  // The mini device buffers are non-default-constructible (the ProgramImpl ctor takes\n"
    "  // them by move) and are NEVER touched in real mode (advance_prefill / decode /\n"
    "  // ensure_pages / store_prefix / restore_prefix all dispatch to real_), so pass\n"
    "  // size-1 sentinels rather than risking a 0-size cudaMalloc.\n"
    "  auto self = std::make_unique<detail::ProgramImpl>(\n"
    "      DeviceArena(1), DeviceBuffer(1), DeviceBuffer(1), DeviceBuffer(1),\n"
    "      PinnedHostBuffer(1), PinnedHostBuffer(1), PinnedHostBuffer(1));\n"
    "\n"
    "  self->real_mode_ = true;\n"
    "  self->real_model_ = std::move(model);\n"
    "  self->real_ = std::make_unique<RealProgram>(self->real_model_->view(), device, max_context,\n"
    "                                              idx_dtype);\n"
    "  self->max_context = max_context;\n"
    "  self->max_concurrency = 1;  // real v1: one recurrent state set => single lane\n"
    "  self->kv_capacity = max_context;  // report-only in real v1 (no mini page pool)\n"
    "  self->kv_total_pages = 0;\n"
    "  self->per_lane_pages = 0;\n"
    "  self->stream = device.stream;\n"
    "  self->device_ordinal = device.device;\n"
    "  self->lanes.resize(1);  // one (inactive) lane; activated by plan_request / the engine\n"
    "\n"
    "  // `new` here runs in create_real_program's context (a friend of the private\n"
    "  // Program ctor); std::make_unique would not have that access.\n"
    "  return std::unique_ptr<Program>(new Program(std::move(self)));\n"
    "}"
)

new = (
    "// M2 real-mode factory from an ALREADY-LOADED model (no second open). The real\n"
    "// 75 GB backbone is H2D'd exactly once across construct_loaded_model +\n"
    "// create_program, so this overload must NOT re-open the artifact. It builds the\n"
    "// proven single-lane RealProgram (self-contained recurrent/KV/MoE state) and\n"
    "// wraps it in the family's Program facade with the mini device buffers as size-1\n"
    "// sentinels (never touched in real mode). `max_context` sizes the RealProgram's QSA\n"
    "// paged-KV pool and the plan_request room; it must be >= the largest prompt the\n"
    "// serve should accept.\n"
    "std::unique_ptr<Program> create_real_program_from_loaded(\n"
    "    std::unique_ptr<RealLoadedModel> model, std::uint32_t max_context,\n"
    "    DeviceContext& device, ops::QsaIndexerKvDtype idx_dtype) {\n"
    "  if (max_context == 0) {\n"
    "    throw std::runtime_error(\"flash_next real: max_context must be > 0\");\n"
    "  }\n"
    "  if (model == nullptr) {\n"
    "    throw std::runtime_error(\"flash_next real: model must be non-null\");\n"
    "  }\n"
    "\n"
    "  // The mini device buffers are non-default-constructible (the ProgramImpl ctor takes\n"
    "  // them by move) and are NEVER touched in real mode (advance_prefill / decode /\n"
    "  // ensure_pages / store_prefix / restore_prefix all dispatch to real_), so pass\n"
    "  // size-1 sentinels rather than risking a 0-size cudaMalloc.\n"
    "  auto self = std::make_unique<detail::ProgramImpl>(\n"
    "      DeviceArena(1), DeviceBuffer(1), DeviceBuffer(1), DeviceBuffer(1),\n"
    "      PinnedHostBuffer(1), PinnedHostBuffer(1), PinnedHostBuffer(1));\n"
    "\n"
    "  self->real_mode_ = true;\n"
    "  self->real_model_ = std::move(model);\n"
    "  self->real_ = std::make_unique<RealProgram>(self->real_model_->view(), device, max_context,\n"
    "                                              idx_dtype);\n"
    "  self->max_context = max_context;\n"
    "  self->max_concurrency = 1;  // real v1: one recurrent state set => single lane\n"
    "  self->kv_capacity = max_context;  // report-only in real v1 (no mini page pool)\n"
    "  self->kv_total_pages = 0;\n"
    "  self->per_lane_pages = 0;\n"
    "  self->stream = device.stream;\n"
    "  self->device_ordinal = device.device;\n"
    "  self->lanes.resize(1);  // one (inactive) lane; activated by plan_request / the engine\n"
    "\n"
    "  // `new` here runs in create_real_program_from_loaded's context (a friend of the\n"
    "  // private Program ctor); std::make_unique would not have that access.\n"
    "  return std::unique_ptr<Program>(new Program(std::move(self)));\n"
    "}\n"
    "\n"
    "// M2 real-mode factory. Opens the real 48x512 artifact + ngram via RealLoadedModel,\n"
    "// then delegates to create_real_program_from_loaded.\n"
    "std::unique_ptr<Program> create_real_program(const std::filesystem::path& artifact,\n"
    "                                             const std::filesystem::path& ngram,\n"
    "                                             std::uint32_t max_context, DeviceContext& device,\n"
    "                                             ops::QsaIndexerKvDtype idx_dtype) {\n"
    "  // `open` throws on a missing/corrupt artifact or a CUDA allocation error.\n"
    "  auto model = RealLoadedModel::open(artifact, ngram, device);\n"
    "  return create_real_program_from_loaded(std::move(model), max_context, device, idx_dtype);\n"
    "}"
)
assert src.count(old) == 1, "create_real_program anchor not found: %d" % src.count(old)
src = src.replace(old, new, 1)

with io.open(path, "w", encoding="utf-8", newline="") as f:
    f.write(src)
print("OK program.cpp")
