F = chr(102)
N = chr(78)
L = []
a = L.append
a("$ErrorActionPreference = 'Continue'\n")
a("$root = 'C:\\Users\\Micke\\Documents\\Kodprojekt\\N" + F + "ner " + F + "lash'\n")
a("$log  = Join-Path $root '.agent\\p1v4_cycle.log'\n")
a("$serveExe = 'C:\\Users\\Micke\\Desktop\\N" + F + "ner AI\\n" + F + "er-serve.exe'\n")
a("$serveArgs = @(\n")
a("  'C:\\Users\\Micke\\Desktop\\N" + F + "ner AI\\models\\qwen3_8_27b_nv" + F + "p4sw" + F + "t.n" + F + "er',\n")
a("  '--host','127.0.0.1','--port','8888',\n")
a("  '--default-max-tokens','8192',\n")
a("  '--preserve-thinking',\n")
a("  '--system-prompt-file','C:\\Users\\Micke\\Desktop\\N" + F + "ner AI\\system-prompt.md',\n")
a("  '--kv-capacity','262144','--max-context','262144','--kv-dtype','" + F + "p8',\n")
a("  '--temperature','1.0','--top-p','0.95','--top-k','20','--min-p','0.0',\n")
a("  '--presence-penalty','0.0','--vision','cpu','--spec','d" + F + "lash2',\n")
a("  '--draft-tokens','7','--lm-head-draft','--default-thinking-budget','6144'\n")
a(")\n")
a("function L($m) { Add-Content -Path $log -Value ((Get-Date).ToString(\"HH:mm:ss\") + ' ' + $m) }\n")
a("L \"CYCLE START\"\n")
a("$procs = @(Get-Process -Name 'n" + F + "er-serve' -ErrorAction SilentlyContinue)\n")
a("foreach ($p in $procs) { L ('Killing serve PID ' + $p.Id); Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue }\n")
a("$d1 = (Get-Date).AddSeconds(120)\n")
a("while ((Get-Process -Name 'n" + F + "er-serve' -ErrorAction SilentlyContinue) -and (Get-Date -lt $d1)) { Start-Sleep -Seconds 2 }\n")
a("$free = -1\n")
a("$d2 = (Get-Date).AddSeconds(120)\n")
a("while ((Get-Date -lt $d2)) {\n")
a("  $free = [int](nvidia-smi --query-gpu=memory." + F + "ree --format=csv,noheader 2>$null | Select-Object -First 1 -replace '[^\\d]','')\n")
a("  if ($free -ge 30000) { break }\n")
a("  Start-Sleep -Seconds 2\n")
a("}\n")
a("L (\"VRAM " + F + "ree MiB=\" + $free)\n")
a("Set-Location $root\n")
a("L \"M3 START\"\n")
a("python .agent\\p1v4_launch.py 2>&1 | Tee-Object -FilePath $log\n")
a("L (\"M3 EXIT \" + $LASTEXITCODE)\n")
a("L \"RESTART SERVE\"\n")
a("Start-Process -FilePath $serveExe -ArgumentList $serveArgs -WindowStyle Hidden\n")
a("L \"SERVE RESTARTED\"\n")
a("L \"CYCLE DONE\"\n")
out = "".join(L)
with io.open(".agent/p1v4_full_cycle.ps1", "w", encoding="utf-8", newline="") as fh:
    fh.write(out)
print("WROTE ps1", len(out), "bytes; f count =", out.count(F))
